---
- name: Atualiza o Sistema Operacional
  command: yum update -y

- name: Desabilita SElinux
  selinux:
    state: disabled

- name: Desabilita o Firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Seta o hostname da máquina
  hostname:
    name: "{{ newhostname }}"
  tags: hostname
