---
- name: Adiciona grupo infra
  group:
    name: infra
    state: present
  tags: user

- name: Adiciona usuarios Infra
  user:
    name="{{ item.id }}" state=present groups=infra shell=/bin/bash comment="{{ item.nome }}"
  with_items: "{{ infrauser }}"
  become: yes
  tags: user

- name: Adiciona grupo dev
  group:
    name: dev
    state: present
  tags: user

- name: Adiciona usuarios dev
  user:
    name="{{ item.id }}" state=present groups=dev shell=/bin/bash comment="{{ item.nome }}"
  with_items: "{{ devuser }}"
  tags: user
  become: yes

- name: criar pasta ssh
  file: path=/home/{{ item.id }}/.ssh state=directory owner={{ item.id }}
  with_items:
    - "{{ infrauser }}"
    - "{{ devuser }}"
  become: yes
  tags: user

- name: copiar chaves para servidor
  copy:
    src: /public_key/{{ item.id }}.txt
    dest: /home/{{ item.id }}/.ssh/authorized_keys
  with_items:
    - "{{ infrauser }}"
    - "{{ devuser }}"
  become: yes
  tags: user
